APPNAME  = mapmos

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/ab102401.lev2.cub \
	  mosaic=$(OUTPUT)/mapmosTruth1.cub \
	  create=true \
	  slat=10.765 \
	  elat=34.445 \
	  slon=219.720 \
	  elon=236.190 > /dev/null;
