APPNAME = camrange

camrangeTruth2.txt.IGNORELINES = From 

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from= $(INPUT)/ab102402.cub \
	  to=$(OUTPUT)/camrangeTruth2.txt > /dev/null;
