SRCS = $(wildcard *.cpp)
OBJS = $(SRCS:%.cpp=%.o)
BINS = $(shell basename `pwd`)

XTRAINCDIRS += -I/home/janderso/tnt120
XTRAINCDIRS += -I/home/janderso/jama121

include $(ISISROOT)/make/isismake.apps
