APPNAME = mapsize

mapsize1.txt.IGNORELINES = Map

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) map=$(INPUT)/I00824006RDR.lev2.cub \
	  option=scale \
	  scale=1000 > $(OUTPUT)/mapsize1.txt;
