APPNAME = skypt

skypt.txt.IGNORELINES = Filename

include $(ISISROOT)/make/isismake.tsts

commands:
	 $(APPNAME) from=$(INPUT)/m0402852.cub \
	  to=$(OUTPUT)/skypt.txt \
	  sample = 10.0  \
	  line = 10.0> /dev/null;
