APPNAME = camrange

camrangeTruth1.txt.IGNORELINES = From 

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from= $(INPUT)/ab102401.cub \
	  to=$(OUTPUT)/camrangeTruth1.txt > /dev/null;
