APPNAME = mocproc

mocprocTruth2.cub.TOLERANCE = 0.0009

include $(ISISROOT)/make/isismake.tsts

commands:
	 $(APPNAME) from=$(INPUT)/ab102402.img \
	  to=$(OUTPUT)/mocprocTruth2.cub 1> /dev/null 2>&1;
