SRCS =  pvltodb.cpp DbPvlMap.cpp DbPvlTable.cpp DbMapParameter.cpp \
        DbPvlMapInsert.cpp
OBJS = $(SRCS:%.cpp=%.o)
BINS = pvltodb

include $(ISISROOT)/make/isismake.apps

#ISISCPPFLAGS += -Wno-long-double

