APPNAME = hiclean

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from=$(INPUT)/PSP_001446_1790_RED2_0 \
	  to=$(OUTPUT)/hiclean_RED0.cub \
	  cleanstats=$(OUTPUT)/hiclean_RED0_stats.txt > /dev/null;
