APPNAME = hical

include $(ISISROOT)/make/isismake.tsts
hical_RED2_0.cub.TOLERANCE = .00000015

commands:
	$(APPNAME) from=$(INPUT)/PSP_001446_1790_RED2_0.cub \
	  to=$(OUTPUT)/hical_RED2_0.cub > /dev/null;
