APPNAME = lrowaccal

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) FROM=$(INPUT)/wac000000dd.crop.vis.even.cub TO=$(OUTPUT)/wac000000dd.cal.vis.even.cub > /dev/null;
	$(APPNAME) FROM=$(INPUT)/wac000000dd.crop.vis.odd.cub TO=$(OUTPUT)/wac000000dd.cal.vis.odd.cub > /dev/null;
