APPNAME = campt

camptTruth1.txt.IGNORELINES = Filename

include $(ISISROOT)/make/isismake.tsts

commands:
	$(APPNAME) from= $(INPUT)/ab102401.cub \
	  to=$(OUTPUT)/camptTruth1.txt \
	  sample=1 \
	  line=1 > /dev/null;
